### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by liyue201** [yi-sun/circom-pairing#20]
When running  `build_finalexp.sh` in `scripts/finalexp`, i got an error

```
Written successfully: ../../build/finalexp/finalexp.r1cs
Written successfully: ../../build/finalexp/finalexp.sym
Written successfully: ../../build/finalexp/finalexp_cpp/finalexp.cpp and ../../build/finalexp/finalexp_cpp/finalexp.dat
Written successfully: ../../build/finalexp/finalexp_cpp/main.cpp, circom.hpp, calcwit.hpp, calcwit.cpp, fr.hpp, fr.cpp, fr.asm and Makefile
Written successfully: ../../build/finalexp/finalexp_js/finalexp.wat
Written successfully: ../../build/finalexp/finalexp_js/finalexp.wasm
Everything went okay, circom safe
DONE (205s)
****GENERATING WITNESS FOR SAMPLE INPUT****
/home/ubuntu/temp/circom-pairing/build/finalexp/finalexp_js/witness_calculator.js:161
                    throw new Error(err);
                          ^

Error: RuntimeError: memory access out of bounds
    at /home/ubuntu/temp/circom-pairing/build/finalexp/finalexp_js/witness_calculator.js:161:27
    at Array.forEach (<anonymous>)
    at WitnessCalculator._doCalculateWitness (/home/ubuntu/temp/circom-pairing/build/finalexp/finalexp_js/witness_calculator.js:136:14)
    at WitnessCalculator.calculateWTNSBin (/home/ubuntu/temp/circom-pairing/build/finalexp/finalexp_js/witness_calculator.js:212:20)
    at /home/ubuntu/temp/circom-pairing/build/finalexp/finalexp_js/generate_witness.js:15:38
DONE (0s)

```

env:

```
circom  v2.1.2
node v16.15.0

```

**Comment by jonathanpwang** [comment]
If possible, can you try rolling back circom to v2.0.3 and see if the same error occurs?

**Comment by liyue201** [comment]
thx，it works
