### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by mmagician** [yi-sun/circom-pairing#25]
When I try to run `yarn test`, I get two errors, seemingly randomly one then the other:
1:
`Error: Valid private key was not found in 8 iterations. PRNG is broken`
2:
```
        1) BLS12-381 AddUnequal
       "before all" hook for "Testing pub0x: 3339240539395647922132421991322702372104238240714654970446972450544700122774591608686968259989190566488330273124811 pub0y: 744432948660790862960036547477967872558191627119039349416174476633481639225724439214668100604022444699284851937061 pub1x: 2353243795496842701316041113541329138110619797319023835340736870267512258421539361031135356743499026261373368056148 pub1y: 2386284284397302244401617256103334501788482552281908316689749363078196783100373026156036019989012473381516939628441 sumx: 281010329837547155460527788170376554035001313203216696860475215599731471847996351412485786466998087344616765622663 sumy: 3248113251337188006918471056082065332680491081105036289307214240898940801141424352933588337491542859099102229201823":
     LinkError: WebAssembly.instantiate(): Import #1 module="runtime" function="printErrorMessage" error: function import requires a callable
      at builder (node_modules/circom_tester/wasm/witness_calculator.js:12:40)
      at async wasm_tester (node_modules/circom_tester/wasm/tester.js:43:16)
      at async Context.<anonymous> (test/bls12-381.test.ts:34:15)
```

Any help on improving testing instructions would be appreciated, thanks!

**Comment by neucc1997** [comment]
ChatGpt helps a lot. I faced the same problem. Then I asked ChatGPT with the error information, and I was asked to install some libraries with "npm install xxx", such as "ffjavascript", and update the dependencies with "npm install circom_tester@latest snarkjs@latest ffjavascript@latest". Finally, it starts to work.
